name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v --enable-code-coverage

    - name: Swift Coverage Conversion
      uses: sersoft-gmbh/swift-coverage-action@v4
      id: coverage-files

    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        flags: unittests
        files: ${{join(fromJSON(steps.coverage-files.outputs.files), ',')}}
